### ISSUE TITLE
show colors cyclenetworks

### ISSUE THREAD

**Issue by xivk** [anyways-open/genk-cycling-frontend#14]
Show the colors of the cyclenetworks again on the route itself:

https://genk.anyways.eu/?loc1=5.467788367497462,50.9631468432772&loc2=5.515338568928144,50.96014653321683&

This route should show the colors of the cyclenetworks when going over them.

**Comment by pietervdvn** [comment]
I've edited `bicycle.lua` (see 1870a5b83dba55148b698bd99859b0517f4ebfd3) to include Genk; this profile has been deployed on the server. This means that network colours should be included into the profile as well, but I don't know if they are included in the response by the server.

**Comment by pietervdvn** [comment]
Fixed in https://github.com/anyways-open/cycling-backend/commit/6f4ba48dec157ab6374278bc1bb50912edc07fee
