### ISSUE TITLE
Add legend

### ISSUE THREAD

**Issue by pietervdvn** [anyways-open/genk-cycling-frontend#20]
Add a frame which shows where each route goes to, what colour it has and (if applicable) what the routenumber is

**Comment by xivk** [comment]
We need something like there was in the previous version of the brussels routeplanner:

![image](https://user-images.githubusercontent.com/1128068/52584703-af88e800-2e2a-11e9-9b3e-4527b1a15c7a.png)

**Comment by xivk** [comment]
Add another button on top next to the hamburger menu to show/hide this but show it by default when the routeplanner is loaded.

**Comment by pietervdvn** [comment]
I've added an initial legend, visible in the genk tab iff no route is loaded. They are clickable, although no action is taken if they are clicked yet.

![Screenshot from 2019-03-21 16-59-59](https://user-images.githubusercontent.com/1466478/54766001-cc1ef980-4bfa-11e9-9582-81401dad5c55.png)
