### ISSUE TITLE
Routing: discourage 'subjectively unsafe roads'?

### ISSUE THREAD

**Issue by pietervdvn** [anyways-open/genk-cycling-frontend#23]
Using [class:bicycle](https://wiki.openstreetmap.org/wiki/Key:class:bicycle) we can mark a few streets (Nieuwstraat, rotondes Europalaan, Landwaartslaan) as 'less preferable' to the routing engine because they are deemed unsafe.

Note that this is subjective, hard to measure on the spot data so not a great fit to add directly to OSM.

**Comment by xivk** [comment]
When looking at the wiki page I don't think we should use this tag. It's highly subjective and some other routing people commented recommending not to use this tag.
