### ISSUE TITLE
Provide icons to pin the site as app

### ISSUE THREAD

**Issue by pietervdvn** [anyways-open/genk-cycling-frontend#3]
For now, when the option 'pin to top sites' is used on mobile, the website will use [this icon](https://github.com/anyways-open/cycling-frontend/blob/master/android-chrome-256x256.png).

We need a Genk-specific replacement for this.

@wimmichiels76: can you ask for one?

**Comment by xivk** [comment]
I think this can be closed no? @pietervdvn

**Comment by pietervdvn** [comment]
Indeed, I missed 5bf88d21b79526556b15ed644cd217d5e3c833a3 which fixes it
