### ISSUE TITLE
Unmapped segments

### ISSUE THREAD

**Issue by xivk** [anyways-open/genk-cycling-frontend#30]
There are some unmapped parts of the yellow cycling network:

https://genk.anyways.eu/staging/?loc1=5.487194,50.962750&loc2=5.450134,50.923108&zoom=15.69&lat=50.944994&lng=5.476104&p=network-genk&

![image](https://user-images.githubusercontent.com/1128068/54124851-6319d380-43fb-11e9-86ea-e727e0e77bf1.png)

https://genk.anyways.eu/staging/?loc1=5.450134,50.923108&loc2=5.487194,50.962750&zoom=15.69&lat=50.944994&lng=5.476104&p=network-genk&

![image](https://user-images.githubusercontent.com/1128068/54124878-7462e000-43fb-11e9-9c22-186633d72ce2.png)

We probable need to map things in both directions or change the cyclepaths to be bidirectional:

![image](https://user-images.githubusercontent.com/1128068/54124933-965c6280-43fb-11e9-94b4-45b1662822aa.png)

**Comment by xivk** [comment]
This changeset also fixes part of this:

https://www.openstreetmap.org/changeset/68071695

**Comment by xivk** [comment]
Leaving this open until #2 is fixed, it's only then we really have fixed everything.

**Comment by pietervdvn** [comment]
Small segments are mapped.
