### ISSUE TITLE
Subtle color differences

### ISSUE THREAD

**Issue by xivk** [anyways-open/genk-cycling-frontend#38]
![image](https://user-images.githubusercontent.com/1128068/54984446-ca608780-4fa6-11e9-9e9a-76b567312835.png)

**Comment by pietervdvn** [comment]
The icons (cross, swap-arrows and menu) are black while the genk-colours are a dark-blue. Is this the difference you mean?

**Comment by xivk** [comment]
No if you look very closely you can see that the background of for example the switch button is not quite white.

**Comment by xivk** [comment]
Background color button: #FAFAFA; not FFFFFF

**Comment by pietervdvn** [comment]
Fixed
