### ISSUE TITLE
update "choose profile tabs"

### ISSUE THREAD

**Issue by wimmichiels76** [anyways-open/genk-cycling-frontend#55]
1. above the tabs, write this line: 
"Welk soort route wil je?"
2. tab names:
tab1:"Fietsnet Genk"  tab2:"Knooppunten" tab3:"Snelste"
tab1 is default
3. update the names of the genk routes to (exact with caps and all like this:):

"1 Diepenbeek en Havenlaan"
"2 Hasselt - Thor Park"
"3 Bokrijk - Genk - Synaps Park - Kattevennen - Zutendaal"
"4 Zonhoven - C-mine - Wiemesmeer"
"5 LABIOMISTA - Zwartberg - Winterslag - Bilzen-Noord"
"6 Hoevenzavel - Zwartberg - Genk-centrum"

4. update the explanation of the tabs to this (exact phrase):

tab 1:
"Fietsnet Genk bestaat uit routes die je aangenaam en snel naar je bestemming brengen." 
tab 2:
"Dit is het bekende toeristische fietsknoopuntennetwerk. Je rijdt via de genummerde knooppunten."
tab 3:
"Dit is de snelste route."

**Comment by xivk** [comment]
This is done except for the ""Welk soort route wil je?"" part.
