### ISSUE TITLE
Give cost estimation for app

### ISSUE THREAD

**Issue by wimmichiels76** [anyways-open/genk-cycling-frontend#59]
What would it cost to turn this website into an app? One extra feature would be a circle on the map showing 'i am here'.

**Comment by xivk** [comment]
After doing some research it seems Apple will reject any app that is just a wrapper of a website. So we cannot submit the app to the iOS app store. We can however do this for Android.

If we want an app for iOS we need to have 'significant native functionality' otherwise the app will be rejected.
