### ISSUE TITLE
Provide 3 instead of 4 different routing options - remove the 'networks' option

### ISSUE THREAD

**Issue by xivk** [anyways-open/genk-cycling-frontend#7]
I think this is also a good idea for us:

https://github.com/oSoc18/bike4brussels/issues/19

**Comment by xivk** [comment]
It is confirmed now with @wimmichiels76 

We should also remove 1 of the options.

**Comment by xivk** [comment]
We should merge "Gebalanceerd" and "Ontspannen" into once called "Ontspannen"

**Comment by pietervdvn** [comment]
I simply removed every mention of 'balanced'. We might tweak the 'relax' routing a little, but I haven't looked into that right now.
