### ISSUE TITLE
Still getting old version

### ISSUE THREAD

**Issue by xivk** [anyways-open/genk-cycling-frontend#8]
When opening the routeplanner in firefox I keep getting the old version:

![image](https://user-images.githubusercontent.com/1128068/49797502-920aa580-fd37-11e8-8882-cb5a5b460e18.png)

Only when hard refreshing I get the new one:
![image](https://user-images.githubusercontent.com/1128068/49797536-a6e73900-fd37-11e8-9de1-e9c6aa362923.png)

But then the crazy starts, when doing a non-hard refresh, I again get the old version!

**Comment by pietervdvn** [comment]
I've had this problem too, in the very beginning when developing on this a few months back. Right now, I can't reproduce on my machine but know that at least you're not crazy.

I suspect that a very old version is still cached somewhere - possibly on your machine.

**Comment by xivk** [comment]
![2018-11-28 19 03 53](https://user-images.githubusercontent.com/1128068/49799670-6c809a80-fd3d-11e8-8b24-367741a5d4dd.jpg)

Same issue on mobile

**Comment by xivk** [comment]
I think this is related to this:

https://stackoverflow.com/questions/37117933/service-workers-not-updating

**Comment by xivk** [comment]
This is now fixed, check the upstream issue.
